### ISSUE TITLE
Error in Compilation

### ISSUE THREAD

**Issue by sylus** [oriuminc/vagrant-ariadne#26]
@patcon This could have just been a one time thing or maybe pear.phpunit.de was down but just in case mentioning here:

``` console

================================================================================
Error executing action `run` on resource 'execute[pear channel-discover pear.phpunit.de]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of pear channel-discover pear.phpunit.de ----
STDOUT: Discovering channel pear.phpunit.de over http:// failed with message: channel-add: Cannot open "http://pear.phpunit.de/channel.xml" (Connection to `pear.phpunit.de:80' failed: php_network_getaddresses: getaddrinfo failed: Name or service not known)
Trying to discover channel pear.phpunit.de over https:// instead
Discovery of channel "pear.phpunit.de" failed (channel-add: Cannot open "https://pear.phpunit.de/channel.xml" (Connection to `pear.phpunit.de:443' failed: php_network_getaddresses: getaddrinfo failed: Name or service not known))
STDERR: 
---- End output of pear channel-discover pear.phpunit.de ----
Ran pear channel-discover pear.phpunit.de returned 1

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear_channel.rb

 29:     Chef::Log.info("Discovering pear channel #{@new_resource}")
 30:     execute "pear channel-discover #{@new_resource.channel_name}" do
 31:       action :run
 32:     end
 33:     new_resource.updated_by_last_action(true)

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear_channel.rb:30:in `class_from_file'

execute("pear channel-discover pear.phpunit.de") do
  retry_delay 2
  cookbook_name :phpunit
  retries 0
  action [:run]
  returns 0
  command "pear channel-discover pear.phpunit.de"
  backup 5
end
```

**Comment by patcon** [comment]
Hm. Might be that the pear site was down. Can you visit manually?

If that's not it, it might be that you pulled changes on master (which upgraded chef in the VM from `v0.10.8` to `v10.14.0`ish in the `Vagrantfile`), but didn't rerun `rake setup`, which would have rerun `librarian-chef install` to install the new standard cookbook versions from `Cheffile.lock` for that Ariadne version (php cookbook needed some bugfixes applied to work on chef versions above 0.10.8, i believe). Sorry, I tried to explain the logic, but long-story-short, try running `rake setup` which is probably the bare minimum to run when you pull changes.

Keep me posted!

**Comment by sylus** [comment]
Seems to work now :) thanks for the guidance!

**Comment by darkoantic** [comment]
Yep, this seem to happen if a channel is not accessible for some reason. Maybe we could add to the docs that on an occasion vagrant up may fail if the resources are not available and that the solution is to run vagrant reload (immediately or wait a bit).

```
================================================================================
Error executing action `install` on resource 'php_pear[PHPUnit]'
================================================================================

Mixlib::ShellOut::CommandTimeout
--------------------------------
command timed out:
---- Begin output of pear -d preferred_state=stable search -c phpunit PHPUnit ----
STDOUT: Retrieving data...0%
....50%....
STDERR: 
---- End output of pear -d preferred_state=stable search -c phpunit PHPUnit ----

Cookbook Trace:
---------------
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear.rb:243:in `pecl?'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear.rb:99:in `load_current_resource'

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/phpunit/recipes/default.rb

 34: 
 35: php_pear "PHPUnit" do
 36:   channel "phpunit"
 37:   version node['phpunit']['version']
 38:   action :install
 39: end

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/phpunit/recipes/default.rb:35:in `from_file'

php_pear("PHPUnit") do
  channel "phpunit"
  retry_delay 2
  preferred_state "stable"
  cookbook_name :phpunit
  version "3.6.10"
  retries 0
  package_name "PHPUnit"
  action [:install]
  recipe_name "default"
end

[Sat, 13 Oct 2012 22:57:44 +0200] ERROR: Running exception handlers
[Sat, 13 Oct 2012 22:57:44 +0200] ERROR: Exception handlers complete
[Sat, 13 Oct 2012 22:57:44 +0200] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[Sat, 13 Oct 2012 22:57:44 +0200] FATAL: Mixlib::ShellOut::CommandTimeout: php_pear[PHPUnit] (phpunit::default line 35) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of pear -d preferred_state=stable search -c phpunit PHPUnit ----
STDOUT: Retrieving data...0%
....50%....
STDERR: 
---- End output of pear -d preferred_state=stable search -c phpunit PHPUnit ----
```

**Comment by sylus** [comment]
Yeah vagrant reload seems to fix it 3/4 of the time :)

**Comment by patcon** [comment]
Ah, actually `rake fix_networking` is likely the root fix. When wifi on the host connects to another network, sometimes the `/etc/init.d/networking` service inside the VM needs a restart, and that rake task does that (taking a little less time than a full `vagrant reload`. Let me know if that has the same affect next time. That should probably be documented more prominently, if anyone can suggest as appropriate place to move it in the readme :)
