### ISSUE TITLE
cookbooks-merge/ariadne/recipes/example.rb breaks on line 44

### ISSUE THREAD

**Issue by calvinte** [oriuminc/vagrant-ariadne#6]
``` sh
[Wed, 23 May 2012 11:31:11 -0700] ERROR: directory[/mnt/www/html] (ariadne::example line 44) has had an error
[Wed, 23 May 2012 11:31:11 -0700] ERROR: directory[/mnt/www/html] (/tmp/vagrant-chef-1/chef-solo-2/cookbooks/ariadne/recipes/example.rb:44:in `from_file') had an error:
 16 #
directory[/mnt/www/html] (ariadne::example line 44) had an error: Errno::EPERM: Operation not permitted - /mnt/www/html
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/file_access_control/unix.rb:114:in `chown'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/file_access_control/unix.rb:114:in `chown'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/file_access_control/unix.rb:84:in `set_group'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/file_access_control/unix.rb:31:in `set_all'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/mixin/enforce_ownership_and_permissions.rb:33:in `enforce_ownership_and_permissions'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/provider/directory.rb:51:in `action_create'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource.rb:454:in `send'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource.rb:454:in `run_action'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/runner.rb:49:in `run_action'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/runner.rb:85:in `converge'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/runner.rb:85:in `each'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/runner.rb:85:in `converge'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/runner.rb:80:in `converge'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/client.rb:330:in `converge'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/client.rb:163:in `run'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/application/solo.rb:207:in `run_application'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/application/solo.rb:195:in `loop'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/application/solo.rb:195:in `run_application'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/../lib/chef/application.rb:70:in `run'
/opt/ruby/lib/ruby/gems/1.8/gems/chef-0.10.10/bin/chef-solo:25
/opt/ruby/bin/chef-solo:19:in `load'
/opt/ruby/bin/chef-solo:19
[Wed, 23 May 2012 11:31:11 -0700] ERROR: Running exception handlers
[Wed, 23 May 2012 11:31:11 -0700] ERROR: Exception handlers complete
[Wed, 23 May 2012 11:31:11 -0700] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[Wed, 23 May 2012 11:31:11 -0700] FATAL: Errno::EPERM: directory[/mnt/www/html] (ariadne::example line 44) had an error: Errno::EPERM: Operation not permitted - /mnt/www/html
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

I just took out that part, couldn't find a quick fix.

**Comment by patcon** [comment]
This resulting from switching folder sharing to NFS (which is waaay faster than native Vbox sharing when working with a drupaly amount of files). The code was still trying to set the owner/group of the shared `/mnt/www/html` directory, which isn't allowed with NFS sharing.

Has already been fixed in my local code, but working through some other things. thanks calvin :)
