### ISSUE TITLE
Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.3 error halts provisioner

### ISSUE THREAD

**Issue by mparker17** [oriuminc/vagrant-ariadne#77]
When I try to `vagrant up` on the develop branch, using the custom basebox, I get the following error:

```
[Sat, 10 Nov 2012 18:35:20 +0100] INFO: Processing php_pear_channel[pear.phpunit.de] action discover (phpunit::default line 25)
[Sat, 10 Nov 2012 18:35:20 +0100] INFO: Discovering pear channel php_pear_channel[pear.phpunit.de]
[Sat, 10 Nov 2012 18:35:20 +0100] INFO: Processing php_pear_channel[pear.phpunit.de] action update (phpunit::default line 25)
[Sat, 10 Nov 2012 18:35:20 +0100] INFO: Processing execute[pear channel-discover pear.phpunit.de] action run (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear_channel.rb line 30)
[Sat, 10 Nov 2012 18:35:21 +0100] INFO: execute[pear channel-discover pear.phpunit.de] ran successfully
[Sat, 10 Nov 2012 18:35:21 +0100] INFO: Processing php_pear_channel[pear.symfony-project.com] action discover (phpunit::default line 25)
[Sat, 10 Nov 2012 18:35:21 +0100] INFO: Discovering pear channel php_pear_channel[pear.symfony-project.com]
[Sat, 10 Nov 2012 18:35:21 +0100] INFO: Processing php_pear_channel[pear.symfony-project.com] action update (phpunit::default line 25)
[Sat, 10 Nov 2012 18:35:21 +0100] INFO: Processing execute[pear channel-discover pear.symfony-project.com] action run (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear_channel.rb line 30)
[Sat, 10 Nov 2012 18:35:22 +0100] INFO: execute[pear channel-discover pear.symfony-project.com] ran successfully
[Sat, 10 Nov 2012 18:35:22 +0100] INFO: Processing php_pear[PEAR-phpunit] action upgrade (phpunit::default line 30)
[Sat, 10 Nov 2012 18:35:24 +0100] INFO: Processing php_pear[PHPUnit] action install (phpunit::default line 35)
[Sat, 10 Nov 2012 18:35:34 +0100] INFO: Installing php_pear[PHPUnit] version 3.6.10

================================================================================
Error executing action `install` on resource 'php_pear[PHPUnit]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of echo -e "\r" | pear -d preferred_state=stable install -a phpunit/PHPUnit-3.6.10 ----
STDOUT: Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.3 found
Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.2 found
install failed
STDERR: 
---- End output of echo -e "\r" | pear -d preferred_state=stable install -a phpunit/PHPUnit-3.6.10 ----
Ran echo -e "\r" | pear -d preferred_state=stable install -a phpunit/PHPUnit-3.6.10 returned 1

Cookbook Trace:
---------------
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear.rb:155:in `pear_shell_out'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear.rb:138:in `install_package'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/php/providers/pear.rb:40:in `class_from_file'

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/phpunit/recipes/default.rb

 34: 
 35: php_pear "PHPUnit" do
 36:   channel "phpunit"
 37:   version node['phpunit']['version']
 38:   action :install
 39: end

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/phpunit/recipes/default.rb:35:in `from_file'

php_pear("PHPUnit") do
  channel "phpunit"
  retry_delay 2
  preferred_state "stable"
  cookbook_name :phpunit
  version "3.6.10"
  retries 0
  package_name "PHPUnit"
  action [:install]
  recipe_name "default"
end

[Sat, 10 Nov 2012 18:36:09 +0100] ERROR: Running exception handlers
[Sat, 10 Nov 2012 18:36:09 +0100] ERROR: Exception handlers complete
[Sat, 10 Nov 2012 18:36:09 +0100] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[Sat, 10 Nov 2012 18:36:09 +0100] FATAL: Mixlib::ShellOut::ShellCommandFailed: php_pear[PHPUnit] (phpunit::default line 35) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of echo -e "\r" | pear -d preferred_state=stable install -a phpunit/PHPUnit-3.6.10 ----
STDOUT: Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.3 found
Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.2 found
install failed
STDERR: 
---- End output of echo -e "\r" | pear -d preferred_state=stable install -a phpunit/PHPUnit-3.6.10 ----
Ran echo -e "\r" | pear -d preferred_state=stable install -a phpunit/PHPUnit-3.6.10 returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by mparker17** [comment]
Looks like it's not just Chef...

```
vagrant@lucid64:~$ sudo pear list-channels
Registered Channels:
====================
Channel                  Alias   Summary
doc.php.net              phpdocs PHP Documentation Team
pear.drush.org           drush   Drush's PEAR Channel Server
pear.php.net             pear    PHP Extension and Application
                                 Repository
pear.phpunit.de          phpunit PHPUnit PEAR Channel
pear.symfony-project.com symfony The symfony project PEAR channel
pecl.php.net             pecl    PHP Extension Community Library
__uri                    __uri   Pseudo-channel for static packages
vagrant@lucid64:~$ sudo pear remote-list -c phpunit
Channel phpunit Available packages:
===================================
Package                           Version
DbUnit                            1.2.1
File_Iterator                     1.3.3
FinderFacade                      1.0.5
Object_Freezer                    1.0.0
PHPUnit                           3.7.9
PHPUnit_MockObject                1.2.2
PHPUnit_Selenium                  1.2.10
PHPUnit_SkeletonGenerator         1.2.0
PHPUnit_Story                     1.0.1
PHPUnit_TestListener_DBUS         1.0.0
PHPUnit_TestListener_XHProf       -n/a-
PHPUnit_TicketListener_Fogbugz    1.0.0
PHPUnit_TicketListener_GitHub     1.0.0
PHPUnit_TicketListener_GoogleCode 1.0.0
PHPUnit_TicketListener_Trac       1.0.0
PHP_CodeBrowser                   1.0.2
PHP_CodeCoverage                  1.2.6
PHP_Invoker                       1.1.2
PHP_Timer                         1.0.4
PHP_TokenStream                   1.1.5
Text_Template                     1.1.4
bytekit                           1.1.3
hphpa                             1.2.2
phpcov                            1.0.0
phpcpd                            1.4.0
phpdcd                            -n/a-
phploc                            1.7.4
ppw                               1.0.4
test_helpers                      1.1.0
vagrant@lucid64:~$ sudo pear install phpunit/PHPUnit
Did not download optional dependencies: phpunit/PHP_Invoker, use --alldeps to download automatically
Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.3 found
Duplicate package channel://pear.phpunit.de/File_Iterator-1.3.2 found
install failed
```

**Comment by mparker17** [comment]
[Apparently, you have to install File_Iterator and Text_Template first](http://stackoverflow.com/a/13077788/198426)... 

```
vagrant@lucid64:~$ sudo pear install phpunit/File_Iterator
downloading File_Iterator-1.3.3.tgz ...
Starting to download File_Iterator-1.3.3.tgz (5,152 bytes)
.....done: 5,152 bytes
install ok: channel://pear.phpunit.de/File_Iterator-1.3.3
vagrant@lucid64:~$ sudo pear install phpunit/Text_Template
downloading Text_Template-1.1.3.tgz ...
Starting to download Text_Template-1.1.3.tgz (3,594 bytes)
....done: 3,594 bytes
install ok: channel://pear.phpunit.de/Text_Template-1.1.3
vagrant@lucid64:~$ sudo pear install phpunit/PHPUnit
Did not download optional dependencies: phpunit/PHP_Invoker, use --alldeps to download automatically
phpunit/PHPUnit can optionally use package "phpunit/PHP_Invoker" (version >= 1.1.0)
phpunit/PHP_CodeCoverage requires package "phpunit/File_Iterator" (version >= 1.3.0, version <= 1.3.2), installed version is 1.3.3
phpunit/PHP_CodeCoverage requires package "phpunit/Text_Template" (version >= 1.1.1, version <= 1.1.2), installed version is 1.1.3
phpunit/PHP_CodeCoverage can optionally use PHP extension "xdebug" (version >= 2.0.5)
phpunit/PHPUnit requires package "phpunit/PHP_CodeCoverage" (version >= 1.1.0)
downloading PHP_Timer-1.0.4.tgz ...
Starting to download PHP_Timer-1.0.4.tgz (3,694 bytes)
....done: 3,694 bytes
downloading PHPUnit_MockObject-1.1.1.tgz ...
Starting to download PHPUnit_MockObject-1.1.1.tgz (19,910 bytes)
...done: 19,910 bytes
downloading YAML-1.0.6.tgz ...
Starting to download YAML-1.0.6.tgz (10,010 bytes)
...done: 10,010 bytes
downloading PHP_TokenStream-1.1.4.tgz ...
Starting to download PHP_TokenStream-1.1.4.tgz (9,877 bytes)
...done: 9,877 bytes
install ok: channel://pear.phpunit.de/PHP_Timer-1.0.4
install ok: channel://pear.phpunit.de/PHPUnit_MockObject-1.1.1
install ok: channel://pear.symfony-project.com/YAML-1.0.6
install ok: channel://pear.phpunit.de/PHP_TokenStream-1.1.4
```

**Comment by mparker17** [comment]
Apparently I need to install Text_Template version 1.1.3 specifically, as 1.1.4 requires PHP 5.3.3 specifically - and lucid64 ships with PHP 5.3.2.

**Comment by mparker17** [comment]
When https://github.com/myplanetdigital/chef-phpunit/pull/1 is merged into `chef-phpunit` and vagrant-ariadne is updated to use that commit, I will close this issue.

I suspect that the latter part will involve updating https://github.com/myplanetdigital/vagrant-ariadne/blob/master/Cheffile#L33
